Transform:
  - AWS::Serverless-2016-10-31
Resources:
  DBSecurityGroupE3B245A3:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS DB Security Group
      SecurityGroupEgress:
        - CidrIp: 255.255.255.255/32
          Description: Disallow all traffic
          FromPort: 252
          IpProtocol: icmp
          ToPort: 86
      SecurityGroupIngress:
        - CidrIp: 10.0.2.0/24
          Description:
            Fn::Join:
              - ""
              - - "Allow AuroraMySQL access from the VPC application subnet cidr 10.0.2.0/24 - "
                - Fn::Select:
                    - 0
                    - Fn::GetAZs: ""
                - " - "
                - Fn::ImportValue: EcsVPCStack:ExportsOutputRefVPCapplicationSubnet1SubnetFE5BD7C4BE303D52
          FromPort: 3306
          IpProtocol: tcp
          ToPort: 3306
        - CidrIp: 10.0.3.0/24
          Description:
            Fn::Join:
              - ""
              - - "Allow AuroraMySQL access from the VPC application subnet cidr 10.0.3.0/24 - "
                - Fn::Select:
                    - 1
                    - Fn::GetAZs: ""
                - " - "
                - Fn::ImportValue: EcsVPCStack:ExportsOutputRefVPCapplicationSubnet2Subnet9AE2E80869DFEB4F
          FromPort: 3306
          IpProtocol: tcp
          ToPort: 3306
      VpcId:
        Fn::ImportValue: EcsVPCStack:ExportsOutputRefVPCB9E5F0B4BD23A326
    Metadata:
      aws:cdk:path: ECSDBClusterStack/DBSecurityGroup/Resource
  DBSecurityGroupfromECSDBClusterStackDbAdminUserSecretRotationSecurityGroup1C361C0DIndirectPort7536E464:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from ECSDBClusterStackDbAdminUserSecretRotationSecurityGroup1C361C0D:{IndirectPort}
      FromPort:
        Fn::GetAtt:
          - DatabaseB269D8BB
          - Endpoint.Port
      GroupId:
        Fn::GetAtt:
          - DBSecurityGroupE3B245A3
          - GroupId
      SourceSecurityGroupId:
        Fn::GetAtt:
          - DbAdminUserSecretRotationSecurityGroupDC60A7AF
          - GroupId
      ToPort:
        Fn::GetAtt:
          - DatabaseB269D8BB
          - Endpoint.Port
    Metadata:
      aws:cdk:path: ECSDBClusterStack/DBSecurityGroup/from ECSDBClusterStackDbAdminUserSecretRotationSecurityGroup1C361C0D:{IndirectPort}
  DBSecurityGroupfromECSDBClusterStackDbUserSecretRotationSecurityGroupF4133348IndirectPortBEB6C5AB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: from ECSDBClusterStackDbUserSecretRotationSecurityGroupF4133348:{IndirectPort}
      FromPort:
        Fn::GetAtt:
          - DatabaseB269D8BB
          - Endpoint.Port
      GroupId:
        Fn::GetAtt:
          - DBSecurityGroupE3B245A3
          - GroupId
      SourceSecurityGroupId:
        Fn::GetAtt:
          - DbUserSecretRotationSecurityGroupACAE4A45
          - GroupId
      ToPort:
        Fn::GetAtt:
          - DatabaseB269D8BB
          - Endpoint.Port
    Metadata:
      aws:cdk:path: ECSDBClusterStack/DBSecurityGroup/from ECSDBClusterStackDbUserSecretRotationSecurityGroupF4133348:{IndirectPort}
  DbAdminUserSecretD9B2AB4A:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description:
        Fn::Join:
          - ""
          - - "Generated by the CDK for stack: "
            - Ref: AWS::StackName
      GenerateSecretString:
        ExcludeCharacters: " %+~`#$&*()|[]{}:;<>?!'/@\"\\"
        GenerateStringKey: password
        PasswordLength: 30
        SecretStringTemplate: '{"username":"dbadminuser"}'
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ECSDBClusterStack/DbAdminUserSecret/Resource
  DbAdminUserSecretAttachmentBDD33DFE:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId:
        Ref: DbAdminUserSecretD9B2AB4A
      TargetId:
        Ref: DatabaseB269D8BB
      TargetType: AWS::RDS::DBCluster
    Metadata:
      aws:cdk:path: ECSDBClusterStack/DbAdminUserSecret/Attachment/Resource
  DbAdminUserSecretAttachmentRotationSchedule27569F58:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      SecretId:
        Ref: DbAdminUserSecretAttachmentBDD33DFE
      RotationLambdaARN:
        Fn::GetAtt:
          - DbAdminUserSecretRotation15C4322E
          - Outputs.RotationLambdaARN
      RotationRules:
        AutomaticallyAfterDays: 30
    Metadata:
      aws:cdk:path: ECSDBClusterStack/DbAdminUserSecret/Attachment/RotationSchedule/Resource
  DbAdminUserSecretAttachmentPolicyC1AC7D98:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      ResourcePolicy:
        Statement:
          - Action: secretsmanager:DeleteSecret
            Effect: Deny
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
            Resource: "*"
        Version: "2012-10-17"
      SecretId:
        Ref: DbAdminUserSecretAttachmentBDD33DFE
    Metadata:
      aws:cdk:path: ECSDBClusterStack/DbAdminUserSecret/Attachment/Policy/Resource
  DbUserSecret7350D430:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description:
        Fn::Join:
          - ""
          - - "Generated by the CDK for stack: "
            - Ref: AWS::StackName
      GenerateSecretString:
        ExcludeCharacters: " %+~`#$&*()|[]{}:;<>?!'/@\"\\"
        GenerateStringKey: password
        PasswordLength: 30
        SecretStringTemplate:
          Fn::Join:
            - ""
            - - '{"username":"dbappuser","masterarn":"'
              - Ref: DbAdminUserSecretD9B2AB4A
              - '"}'
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ECSDBClusterStack/DbUserSecret/Resource
  DbUserSecretAttachmentBD5A92FF:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId:
        Ref: DbUserSecret7350D430
      TargetId:
        Ref: DatabaseB269D8BB
      TargetType: AWS::RDS::DBCluster
    Metadata:
      aws:cdk:path: ECSDBClusterStack/DbUserSecret/Attachment/Resource
  DbUserSecretAttachmentRotationSchedule195BD7D2:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      SecretId:
        Ref: DbUserSecretAttachmentBD5A92FF
      RotationLambdaARN:
        Fn::GetAtt:
          - DbUserSecretRotationFED095FD
          - Outputs.RotationLambdaARN
      RotationRules:
        AutomaticallyAfterDays: 30
    Metadata:
      aws:cdk:path: ECSDBClusterStack/DbUserSecret/Attachment/RotationSchedule/Resource
  DbUserSecretAttachmentPolicyABFA413B:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      ResourcePolicy:
        Statement:
          - Action: secretsmanager:DeleteSecret
            Effect: Deny
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
            Resource: "*"
        Version: "2012-10-17"
      SecretId:
        Ref: DbUserSecretAttachmentBD5A92FF
    Metadata:
      aws:cdk:path: ECSDBClusterStack/DbUserSecret/Attachment/Policy/Resource
  DatabaseSubnets56F17B9A:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for Database database
      SubnetIds:
        - Fn::ImportValue: EcsVPCStack:ExportsOutputRefVPCrdsSubnet1Subnet6ED1A3D44B631178
        - Fn::ImportValue: EcsVPCStack:ExportsOutputRefVPCrdsSubnet2Subnet7BC222EF915291DF
    Metadata:
      aws:cdk:path: ECSDBClusterStack/Database/Subnets/Default
  DatabaseB269D8BB:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      CopyTagsToSnapshot: true
      DBClusterParameterGroupName: default.aurora-mysql5.7
      DBSubnetGroupName:
        Ref: DatabaseSubnets56F17B9A
      EngineVersion: 5.7.mysql_aurora.2.10.1
      MasterUsername:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Ref: DbAdminUserSecretD9B2AB4A
            - :SecretString:username::}}
      MasterUserPassword:
        Fn::Join:
          - ""
          - - "{{resolve:secretsmanager:"
            - Ref: DbAdminUserSecretD9B2AB4A
            - :SecretString:password::}}
      StorageEncrypted: true
      VpcSecurityGroupIds:
        - Fn::GetAtt:
            - DBSecurityGroupE3B245A3
            - GroupId
    UpdateReplacePolicy: Snapshot
    DeletionPolicy: Snapshot
    Metadata:
      aws:cdk:path: ECSDBClusterStack/Database/Resource
  DatabaseInstance1844F58FD:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.r6g.large
      DBClusterIdentifier:
        Ref: DatabaseB269D8BB
      DBSubnetGroupName:
        Ref: DatabaseSubnets56F17B9A
      EnablePerformanceInsights: true
      Engine: aurora-mysql
      EngineVersion: 5.7.mysql_aurora.2.10.1
      PerformanceInsightsRetentionPeriod: 7
      PubliclyAccessible: false
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ECSDBClusterStack/Database/Instance1
  DatabaseInstance2AA380DEE:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.r6g.large
      DBClusterIdentifier:
        Ref: DatabaseB269D8BB
      DBSubnetGroupName:
        Ref: DatabaseSubnets56F17B9A
      EnablePerformanceInsights: true
      Engine: aurora-mysql
      EngineVersion: 5.7.mysql_aurora.2.10.1
      PerformanceInsightsRetentionPeriod: 7
      PubliclyAccessible: false
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ECSDBClusterStack/Database/Instance2
  DbAdminUserSecretRotationSecurityGroupDC60A7AF:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECSDBClusterStack/DbAdminUserSecretRotation/SecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId:
        Fn::ImportValue: EcsVPCStack:ExportsOutputRefVPCB9E5F0B4BD23A326
    Metadata:
      aws:cdk:path: ECSDBClusterStack/DbAdminUserSecretRotation/SecurityGroup/Resource
  DbAdminUserSecretRotation15C4322E:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId:
          Fn::FindInMap:
            - DbAdminUserSecretRotationSARMapping90B97815
            - Ref: AWS::Partition
            - applicationId
        SemanticVersion:
          Fn::FindInMap:
            - DbAdminUserSecretRotationSARMapping90B97815
            - Ref: AWS::Partition
            - semanticVersion
      Parameters:
        endpoint:
          Fn::Join:
            - ""
            - - https://secretsmanager.
              - Ref: AWS::Region
              - "."
              - Ref: AWS::URLSuffix
        functionName: ECSDBClusterStackDbAdminUserSecretRotationD83612FD
        vpcSubnetIds:
          Fn::Join:
            - ""
            - - Fn::ImportValue: EcsVPCStack:ExportsOutputRefVPCapplicationSubnet1SubnetFE5BD7C4BE303D52
              - ","
              - Fn::ImportValue: EcsVPCStack:ExportsOutputRefVPCapplicationSubnet2Subnet9AE2E80869DFEB4F
        vpcSecurityGroupIds:
          Fn::GetAtt:
            - DbAdminUserSecretRotationSecurityGroupDC60A7AF
            - GroupId
    Metadata:
      aws:cdk:path: ECSDBClusterStack/DbAdminUserSecretRotation/Resource
  DbUserSecretRotationSecurityGroupACAE4A45:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECSDBClusterStack/DbUserSecretRotation/SecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId:
        Fn::ImportValue: EcsVPCStack:ExportsOutputRefVPCB9E5F0B4BD23A326
    Metadata:
      aws:cdk:path: ECSDBClusterStack/DbUserSecretRotation/SecurityGroup/Resource
  DbUserSecretRotationFED095FD:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId:
          Fn::FindInMap:
            - DbUserSecretRotationSARMappingAD103F53
            - Ref: AWS::Partition
            - applicationId
        SemanticVersion:
          Fn::FindInMap:
            - DbUserSecretRotationSARMappingAD103F53
            - Ref: AWS::Partition
            - semanticVersion
      Parameters:
        endpoint:
          Fn::Join:
            - ""
            - - https://secretsmanager.
              - Ref: AWS::Region
              - "."
              - Ref: AWS::URLSuffix
        functionName: ECSDBClusterStackDbUserSecretRotationF3A8AA18
        vpcSubnetIds:
          Fn::Join:
            - ""
            - - Fn::ImportValue: EcsVPCStack:ExportsOutputRefVPCapplicationSubnet1SubnetFE5BD7C4BE303D52
              - ","
              - Fn::ImportValue: EcsVPCStack:ExportsOutputRefVPCapplicationSubnet2Subnet9AE2E80869DFEB4F
        vpcSecurityGroupIds:
          Fn::GetAtt:
            - DbUserSecretRotationSecurityGroupACAE4A45
            - GroupId
        masterSecretArn:
          Ref: DbAdminUserSecretAttachmentBDD33DFE
    Metadata:
      aws:cdk:path: ECSDBClusterStack/DbUserSecretRotation/Resource
  rdsScalingRole4458C55C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: application-autoscaling.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: ECSDBClusterStack/rdsScaling/Role/Resource
  rdsScaling2ABCEA5E:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 3
      MinCapacity: 2
      ResourceId:
        Fn::Join:
          - ""
          - - "cluster:"
            - Ref: DatabaseB269D8BB
      RoleARN:
        Fn::GetAtt:
          - rdsScalingRole4458C55C
          - Arn
      ScalableDimension: rds:cluster:ReadReplicaCount
      ServiceNamespace: rds
    Metadata:
      aws:cdk:path: ECSDBClusterStack/rdsScaling/Resource
  rdsScalingrdsScalingTracking45382168:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: ECSDBClusterStackrdsScalingrdsScalingTrackingAEB2F51D
      PolicyType: TargetTrackingScaling
      ScalingTargetId:
        Ref: rdsScaling2ABCEA5E
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: RDSReaderAverageCPUUtilization
        TargetValue: 60
    Metadata:
      aws:cdk:path: ECSDBClusterStack/rdsScaling/rdsScalingTracking/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/31S207DMAz9Ft6zjFLEM7sItAck1O4H3NR02dpkShzQVOXfcRu6iybxFPvYxz0+dSb7LM/l48Mr/PiZqg9zZR3KviRQB7GyxpMLisTqyxTobXAKh5gLtSZtTRRZ/nxN74egR/XEM1AFp+n07mw4Dqz/gY1pHHofhau97NdAUIFHbnFIYkpXbfCETpShMkjnQevlHTB1jsmG9wCjMAo/zvMdGGjQyT6pGD6Rni24BmlBvP+uQ0Pi3HBXKSzB4EGpdliHdjTmDptc+7StVqdrH/+QNHzisUDoJHctjkcuj5hooatqkG/BqCFfsg8CLnUIZL2CVpuGTecAqhaT2lH9LZKereP/y4Qy8S7qboAoNKvpCzst12KMIl3I9Tl8sBomRS4aW6Pc+/l39iKz4bD2XuuZC4Z0h7JI7y8vZFPVdgIAAA==
    Metadata:
      aws:cdk:path: ECSDBClusterStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Mappings:
  DbAdminUserSecretRotationSARMapping90B97815:
    aws:
      applicationId: arn:aws:serverlessrepo:us-east-1:297356227824:applications/SecretsManagerRDSMySQLRotationSingleUser
      semanticVersion: 1.1.60
    aws-cn:
      applicationId: arn:aws-cn:serverlessrepo:cn-north-1:193023089310:applications/SecretsManagerRDSMySQLRotationSingleUser
      semanticVersion: 1.1.37
  DbUserSecretRotationSARMappingAD103F53:
    aws:
      applicationId: arn:aws:serverlessrepo:us-east-1:297356227824:applications/SecretsManagerRDSPostgreSQLRotationMultiUser
      semanticVersion: 1.1.60
    aws-cn:
      applicationId: arn:aws-cn:serverlessrepo:cn-north-1:193023089310:applications/SecretsManagerRDSPostgreSQLRotationMultiUser
      semanticVersion: 1.1.37
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

